name: CI
on: push

jobs:
  gofmt:
    runs-on: ubuntu-latest
    name: check format before running tests
    steps:
      - name: checkout new code
        uses: actions/checkout@v2
        with: # code from pull request
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: load dependency for gofmt
        uses: actions/setup-go@v2
      - name: run gofmt test script
        shell: bash
        run: ./scripts/gofmt_check.sh