name: CI
on: push

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: check format before running tests
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
        with: # code from pull request
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        run: |
          sh ./scripts/gofmt_check.sh